   <!-- Begin Random Image Coding -->
    
    
  
<!--

/*
Random Image Link Script- By JavaScript Kit(http://www.javascriptkit.com) 
Over 200+ free JavaScripts here!
Updated: 00/04/25
*/

function random_imglink(){
var myimages=new Array()
//specify random images below. You can have as many as you wish
myimages[1]="pictures/panoramics/2010/adriatic_sea.jpg"
myimages[2]="pictures/panoramics/2010/alpenrose_alps.jpg"
myimages[3]="pictures/panoramics/2010/amsterdam_canal.jpg"
myimages[4]="pictures/panoramics/2010/anakena_bch_easter_island.jpg"
myimages[5]="pictures/panoramics/2010/barn_austria.jpg"
myimages[6]="pictures/panoramics/2010/broome_au.jpg"
myimages[7]="pictures/panoramics/2010/canadian_rockies.jpg"
myimages[8]="pictures/panoramics/2010/candle_maui.jpg"
myimages[9]="pictures/panoramics/2010/clean_ocean_waves.jpg"
myimages[10]="pictures/panoramics/2010/costa_rica01.jpg"

myimages[11]="pictures/panoramics/2010/disneyworld.jpg"
myimages[12]="pictures/panoramics/2010/el_calafate01.jpg"
myimages[13]="pictures/panoramics/2010/ellaid_mald.jpg"
myimages[14]="pictures/panoramics/2010/fenway.jpg"
myimages[15]="pictures/panoramics/2010/firework_display.jpg"
myimages[16]="pictures/panoramics/2010/Foiano_di_val_Fortore_Southern_Italy.jpg"
myimages[17]="pictures/panoramics/2010/friendship highway - xigaza - tibet.jpg"
myimages[18]="pictures/panoramics/2010/guessthisone.jpg"
myimages[19]="pictures/panoramics/2010/hanauma.jpg"
myimages[20]="pictures/panoramics/2010/harbor_miami_fl.jpg"

myimages[21]="pictures/panoramics/2010/Hong-Kong.jpg"
myimages[22]="pictures/panoramics/2010/hongkong_day.jpg"
myimages[23]="pictures/panoramics/2010/incoming waves.jpg"
myimages[24]="pictures/panoramics/2010/island_archway_gor_vic_aus.jpg"
myimages[25]="pictures/panoramics/2010/japanese_gardens.jpg"
myimages[26]="pictures/panoramics/2010/junglejoy.jpg"
myimages[27]="pictures/panoramics/2010/kophiphi_01.jpg"
myimages[28]="pictures/panoramics/2010/krimmler_waterfall.jpg"
myimages[29]="pictures/panoramics/2010/L0pud Island Bay Cr0atia.jpg"
myimages[30]="pictures/panoramics/2010/la_silla_obs.jpg"

myimages[31]="pictures/panoramics/2010/lake_louise.jpg"
myimages[32]="pictures/panoramics/2010/lhasa_tibet.jpg"
myimages[33]="pictures/panoramics/2010/lighthouse_maine.jpg"
myimages[34]="pictures/panoramics/2010/Loiza Puerto Rico.jpg"
myimages[35]="pictures/panoramics/2010/Madang_PapaNewGuinea.jpg"
myimages[36]="pictures/panoramics/2010/marbella_spain.jpg"
myimages[37]="pictures/panoramics/2010/mccall golf course.jpg"
myimages[38]="pictures/panoramics/2010/mckinnon pass - milford - nz.jpg"
myimages[39]="pictures/panoramics/2010/me-lbourne at night.jpg"
myimages[40]="pictures/panoramics/2010/meteor_crater_az.jpg"

myimages[41]="pictures/panoramics/2010/mittens_arizona.jpg"
myimages[42]="pictures/panoramics/2010/mogoll0n_rim.jpg"
myimages[43]="pictures/panoramics/2010/montana.jpg"
myimages[44]="pictures/panoramics/2010/moon_surface.jpg"
myimages[45]="pictures/panoramics/2010/napa_valley_ca.jpg"
myimages[46]="pictures/panoramics/2010/nice_sunset.jpg"
myimages[47]="pictures/panoramics/2010/northlts.jpg"
myimages[48]="pictures/panoramics/2010/nyny_vegas.jpg"
myimages[49]="pictures/panoramics/2010/opnrd.jpg"
myimages[50]="pictures/panoramics/2010/perth_australia.jpg"

myimages[51]="pictures/panoramics/2010/picturesque_beach.jpg"
myimages[52]="pictures/panoramics/2010/portland_or.jpg"
myimages[53]="pictures/panoramics/2010/quebec_can.jpg"
myimages[54]="pictures/panoramics/2010/queenstown.jpg"
myimages[55]="pictures/panoramics/2010/somewhere_caribbean.jpg"
myimages[56]="pictures/panoramics/2010/sparks_m3adow_or.jpg"
myimages[57]="pictures/panoramics/2010/star_valley_wyoming.jpg"
myimages[58]="pictures/panoramics/2010/swifts_creek_victoria_aus.jpg"
myimages[59]="pictures/panoramics/2010/sydaus.jpg"
myimages[60]="pictures/panoramics/2010/tahiti.jpg"

myimages[61]="pictures/panoramics/2010/tulips_woodburn_or.jpg"
myimages[62]="pictures/panoramics/2010/tynset sentrum osterdalen norway.jpg"
myimages[63]="pictures/panoramics/2010/urquahartcastle_scotland.jpg"
myimages[64]="pictures/panoramics/2010/venice_floating-houses.jpg"
myimages[65]="pictures/panoramics/2010/watson_mill_bridge_st_park.jpg"
myimages[66]="pictures/panoramics/2010/sgurr_fiona_scotland.jpg"
myimages[67]="pictures/panoramics/2010/deans_blue_hole_bahamas.jpg"
myimages[68]="pictures/panoramics/2010/thailand01.jpg"
myimages[69]="pictures/panoramics/2010/tagebau_garzweiler_germany.jpg"
myimages[70]="pictures/panoramics/2010/cape_cove_oregon.jpg"

myimages[71]="pictures/panoramics/2010/dawn_swifts_creek_au.jpg"
myimages[72]="pictures/panoramics/2010/San_Diego.jpg"
myimages[73]="pictures/panoramics/2010/taiping_lake_gardens_malaysia.jpg"
myimages[74]="pictures/panoramics/2010/regensburg_germany.jpg"
myimages[75]="pictures/panoramics/2010/monument_valley.jpg"
myimages[76]="pictures/panoramics/2010/ruppberg_sonnenaufgang_de.jpg"
myimages[77]="pictures/panoramics/2010/sossusvlei_namibia.jpg"
myimages[78]="pictures/panoramics/2010/seine_france.jpg"
myimages[79]="pictures/panoramics/2010/toledo_spain.jpg"
myimages[80]="pictures/panoramics/2010/apollo_17_mission.jpg"

myimages[81]="pictures/panoramics/2010/blacktusk.jpg"
myimages[82]="pictures/panoramics/2010/patagonia_first_blue_light.jpg"
myimages[83]="pictures/panoramics/2010/yosemite_panoramic.jpg"
myimages[84]="pictures/panoramics/2010/prismatic_spring_stitch_yellowstone.jpg"
myimages[85]="pictures/panoramics/2010/cuzco_peru.jpg"
myimages[86]="pictures/panoramics/2010/dry_falls_wa.jpg"
myimages[87]="pictures/panoramics/2010/san_francisco.jpg"
myimages[88]="pictures/panoramics/2010/gorges_du_tarn_pointe_france.jpg"
myimages[89]="pictures/panoramics/2010/san-sebastian-spain.jpg"

/* Begin 2011 */

myimages[90]="pictures/panoramics/2011/1913_wash_bball.jpg"
myimages[91]="pictures/panoramics/2011/arizona-sunset-panoramic.jpg"
myimages[92]="pictures/panoramics/2011/cadiz-spain-panoramic.jpg"
myimages[93]="pictures/panoramics/2011/camp-richardson-lake-tahoe.jpg"
myimages[94]="pictures/panoramics/2011/chapman-beach-guantanamo-bay-cuba.jpg"
myimages[95]="pictures/panoramics/2011/cologne-germany.jpg"
myimages[96]="pictures/panoramics/2011/dinner-plain-summmer-panoramic.jpg"
myimages[97]="pictures/panoramics/2011/east-shore-lake-tahoe.jpg"
myimages[98]="pictures/panoramics/2011/fall-drake-park-deschutes-river-oregon.jpg"
myimages[99]="pictures/panoramics/2011/giza-plateau-egypt-panoramic.jpg"

myimages[100]="pictures/panoramics/2011/hanalei-valley-kauaii.jpg"
myimages[101]="pictures/panoramics/2011/hanko-finland-panoramic.jpg"
myimages[102]="pictures/panoramics/2011/mt-everest-panoramic.jpg"
myimages[103]="pictures/panoramics/2011/pioneer-hut-new-zealand.jpg"
myimages[104]="pictures/panoramics/2011/porto-portugal-panoramic.jpg"
myimages[105]="pictures/panoramics/2011/sedona-arizona-panoramic.jpg"
myimages[106]="pictures/panoramics/2011/summit-mammoth-panoramic.jpg"
myimages[107]="pictures/panoramics/2011/summit-mammoth-panoramic-2.jpg"
myimages[108]="pictures/panoramics/2011/summit-mammoth-panoramic-3.jpg"
myimages[109]="pictures/panoramics/2011/upper-truckee-river-lake-tahoe.jpg"

/* Begin 2009 */

myimages[110]="pictures/panoramics/2009/hongkong_night.jpg"
myimages[111]="pictures/panoramics/2009/nyc_central_park.jpg"
myimages[112]="pictures/panoramics/2009/swifts_cr-eek_victoria_oz.jpg"

/* Begin 2008 */

myimages[113]="pictures/panoramics/2008/big-spring-huntsville-alabama-panoramic.jpg"
myimages[114]="pictures/panoramics/2008/eden-project-geodesic-domes.jpg"
myimages[115]="pictures/panoramics/2008/fraser-river-british-columbia.jpg"
myimages[116]="pictures/panoramics/2008/hacha-grande-from-papagayo.jpg"
myimages[117]="pictures/panoramics/2008/high-speed-rail-europe.jpg"
myimages[118]="pictures/panoramics/2008/international-space-station-panoramic.jpg"
myimages[119]="pictures/panoramics/2008/nubble-light.jpg"
myimages[120]="pictures/panoramics/2008/royal-gorge-colorado-panoramic.jpg"
myimages[121]="pictures/panoramics/2008/south-pole.jpg"
myimages[122]="pictures/panoramics/2008/tex-rangers.jpg"
myimages[123]="pictures/panoramics/2008/turks-caicos01.jpg"
myimages[124]="pictures/panoramics/2008/turks-caicos02.jpg"

/* Begin 2014 */

myimages[125]="pictures/panoramics/2014/01-Adirondack-Park-New-York.jpg"
myimages[126]="pictures/panoramics/2014/02-Emerald-Lake-Yukon.jpg"
myimages[127]="pictures/panoramics/2014/03-Harrison-Lake-Iceland.jpg"
myimages[128]="pictures/panoramics/2014/04-Sprague-Lake.jpg"
myimages[129]="pictures/panoramics/2014/05-Strusta-Lake.jpg"
myimages[130]="pictures/panoramics/2014/06-Roselend-Lake-France.jpg"
myimages[131]="pictures/panoramics/2014/07-Dawn-RhodeIsland.jpg"
myimages[132]="pictures/panoramics/2014/08-Kathu-Phuket.jpg"
myimages[133]="pictures/panoramics/2014/09-ArtShowFinalist-Africa.jpg"
myimages[134]="pictures/panoramics/2014/10-Xinjiang-China.jpg"
myimages[135]="pictures/panoramics/2014/11-Acacia-Trees-Amboseli-Kenya.jpg"
myimages[136]="pictures/panoramics/2014/12-Wyoming1.jpg"
myimages[137]="pictures/panoramics/2014/13-northern-australia.jpg"
myimages[138]="pictures/panoramics/2014/14-newhampshire.jpg"
myimages[139]="pictures/panoramics/2014/15-sw-wisconsin.jpg"
myimages[140]="pictures/panoramics/2014/16-waverley-hills-winery-south-africa.jpg"
myimages[141]="pictures/panoramics/2014/17-ocotillo-golf-course.jpg"
myimages[142]="pictures/panoramics/2014/18-moraine-lake-alberta.jpg"
myimages[143]="pictures/panoramics/2014/19-scotland.jpg"
myimages[144]="pictures/panoramics/2014/20-scotland-country-lake.jpg"
myimages[145]="pictures/panoramics/2014/21-grand-canyon.jpg"



//specify corresponding links below
var imagelinks=new Array()
imagelinks[1]="http://en.wikipedia.org/wiki/Adriatic_Sea"
imagelinks[2]="http://en.wikipedia.org/wiki/Western_Alps"
imagelinks[3]="http://en.wikipedia.org/wiki/Canals_of_Amsterdam"
imagelinks[4]="http://en.wikipedia.org/wiki/Anakena"
imagelinks[5]="http://en.wikipedia.org/wiki/Barn"
imagelinks[6]="http://en.wikipedia.org/wiki/Broome,_Western_Australia"
imagelinks[7]="http://en.wikipedia.org/wiki/Canadian_Rockies"
imagelinks[8]="http://en.wikipedia.org/wiki/Memorial_candle"
imagelinks[9]="http://en.wikipedia.org/wiki/Atlantic_ocean"
imagelinks[10]="http://en.wikipedia.org/wiki/Manuel_Antonio_National_Park"

imagelinks[11]="http://en.wikipedia.org/wiki/Disney_world"
imagelinks[12]="http://en.wikipedia.org/wiki/El_Calafate"
imagelinks[13]="http://en.wikipedia.org/wiki/Maldives"
imagelinks[14]="http://en.wikipedia.org/wiki/Fenway"
imagelinks[15]="http://en.wikipedia.org/wiki/Fireworks"
imagelinks[16]="http://en.wikipedia.org/wiki/Tuscany"
imagelinks[17]="http://en.wikipedia.org/wiki/Friendship_Highway_(Tibet)"
imagelinks[18]="javascript:history.go(0)"
imagelinks[19]="http://en.wikipedia.org/wiki/Hanauma_Bay"
imagelinks[20]="http://en.wikipedia.org/wiki/Bal_Harbour,_Florida"

imagelinks[21]="http://en.wikipedia.org/wiki/Hong_kong"
imagelinks[22]="http://en.wikipedia.org/wiki/Hong_kong"
imagelinks[23]="javascript:history.go(0)"
imagelinks[24]="http://en.wikipedia.org/wiki/Loch_Ard_Gorge"
imagelinks[25]="http://en.wikipedia.org/wiki/Portland_Japanese_Garden"
imagelinks[26]="http://en.wikipedia.org/wiki/Oil_painting"
imagelinks[27]="http://en.wikipedia.org/wiki/Phi_Phi_Islands"
imagelinks[28]="http://en.wikipedia.org/wiki/Krimml_Waterfalls"
imagelinks[29]="http://en.wikipedia.org/wiki/Lopud"
imagelinks[30]="http://en.wikipedia.org/wiki/La_Silla_Observatory"

imagelinks[31]="http://en.wikipedia.org/wiki/Lake_Louise,_Alberta"
imagelinks[32]="http://en.wikipedia.org/wiki/Lhasa"
imagelinks[33]="http://en.wikipedia.org/wiki/Maine"
imagelinks[34]="http://en.wikipedia.org/wiki/Lo%C3%ADza,_Puerto_Rico"
imagelinks[35]="http://en.wikipedia.org/wiki/Madang_Province"
imagelinks[36]="http://en.wikipedia.org/wiki/Marbella"
imagelinks[37]="http://www.mccallgolfclub.com"
imagelinks[38]="http://en.wikipedia.org/wiki/Mackinnon_Pass"
imagelinks[39]="http://en.wikipedia.org/wiki/Melbourne"
imagelinks[40]="http://en.wikipedia.org/wiki/Meteor_Crater"

imagelinks[41]="http://en.wikipedia.org/wiki/Monument_Valley"
imagelinks[42]="http://en.wikipedia.org/wiki/Mogollon_Rim"
imagelinks[43]="http://en.wikipedia.org/wiki/Montana_Mountain"
imagelinks[44]="http://en.wikipedia.org/wiki/Moon"
imagelinks[45]="http://en.wikipedia.org/wiki/Napa_County,_California"
imagelinks[46]="http://en.wikipedia.org/wiki/Sunset"
imagelinks[47]="http://en.wikipedia.org/wiki/Aurora_(astronomy)"
imagelinks[48]="http://en.wikipedia.org/wiki/New_York-New_York_Hotel_&_Casino"
imagelinks[49]="http://en.wikipedia.org/wiki/Trans-Canada_Highway"
imagelinks[50]="http://en.wikipedia.org/wiki/Perth,_Western_Australia"

imagelinks[51]="javascript:history.go(0)"
imagelinks[52]="http://en.wikipedia.org/wiki/Portland,_Oregon"
imagelinks[53]="http://en.wikipedia.org/wiki/Quebec"
imagelinks[54]="http://en.wikipedia.org/wiki/Queenstown,_New_Zealand"
imagelinks[55]="http://en.wikipedia.org/wiki/Caribbean"
imagelinks[56]="http://en.wikipedia.org/wiki/Bend,_Oregon"
imagelinks[57]="http://en.wikipedia.org/wiki/Star_Valley"
imagelinks[58]="http://en.wikipedia.org/wiki/Swifts_Creek,_Victoria"
imagelinks[59]="http://en.wikipedia.org/wiki/Sydney"
imagelinks[60]="http://en.wikipedia.org/wiki/Tahiti"

imagelinks[61]="http://en.wikipedia.org/wiki/Woodburn,_Oregon"
imagelinks[62]="http://en.wikipedia.org/wiki/Tynset"
imagelinks[63]="http://en.wikipedia.org/wiki/Urquhart_Castle"
imagelinks[64]="http://en.wikipedia.org/wiki/Venice"
imagelinks[65]="http://en.wikipedia.org/wiki/Watson_Mill_Bridge_State_Park"
imagelinks[66]="http://en.wikipedia.org/wiki/An_Teallach"
imagelinks[67]="http://en.wikipedia.org/wiki/Dean's_Blue_Hole"
imagelinks[68]="http://en.wikipedia.org/wiki/Thailand"
imagelinks[69]="http://de.wikipedia.org/wiki/Tagebau_Garzweiler"
imagelinks[70]="http://en.wikipedia.org/wiki/Florence,_Oregon"

imagelinks[71]="http://en.wikipedia.org/wiki/Swifts_Creek,_Victoria"
imagelinks[72]="http://en.wikipedia.org/wiki/San_Diego"
imagelinks[73]="http://en.wikipedia.org/wiki/Taiping_Lake_Gardens"
imagelinks[74]="http://en.wikipedia.org/wiki/Regensburg"
imagelinks[75]="http://en.wikipedia.org/wiki/Monument_Valley"
imagelinks[76]="http://de.wikipedia.org/wiki/Ruppberg"
imagelinks[77]="http://en.wikipedia.org/wiki/Sossusvlei"
imagelinks[78]="http://en.wikipedia.org/wiki/Seine"
imagelinks[79]="http://en.wikipedia.org/wiki/Toledo,_Spain"
imagelinks[80]="http://en.wikipedia.org/wiki/Apollo_17"

imagelinks[81]="http://en.wikipedia.org/wiki/Black_Tusk"
imagelinks[82]="http://en.wikipedia.org/wiki/Patagonia"
imagelinks[83]="http://en.wikipedia.org/wiki/Patagonia"
imagelinks[84]="http://en.wikipedia.org/wiki/Yellowstone_National_Park"
imagelinks[85]="http://en.wikipedia.org/wiki/Cusco"
imagelinks[86]="http://en.wikipedia.org/wiki/Dry_Falls"
imagelinks[87]="http://en.wikipedia.org/wiki/San_Francisco"
imagelinks[88]="http://en.wikipedia.org/wiki/Verdon_Gorge"
imagelinks[89]="http://en.wikipedia.org/wiki/San_Sebasti%C3%A1n"

imagelinks[90]="http://en.wikipedia.org/wiki/1913_Washington_Senators_season"
imagelinks[91]="http://en.wikipedia.org/wiki/Arizona_desert"
imagelinks[92]="http://en.wikipedia.org/wiki/Cadiz"
imagelinks[93]="http://en.wikipedia.org/wiki/Lake_Tahoe"
imagelinks[94]="http://en.wikipedia.org/wiki/Cuba"
imagelinks[95]="http://en.wikipedia.org/wiki/Cologne"
imagelinks[96]="javascript:history.go(0)"
imagelinks[97]="http://en.wikipedia.org/wiki/Lake_Tahoe"
imagelinks[98]="http://en.wikipedia.org/wiki/Deschutes_River_(Oregon)"
imagelinks[99]="http://en.wikipedia.org/wiki/Great_Pyramid_of_Giza"

imagelinks[100]="http://en.wikipedia.org/wiki/Hanalei,_Hawaii"
imagelinks[101]="http://en.wikipedia.org/wiki/Hanko"
imagelinks[102]="http://en.wikipedia.org/wiki/Mount_Everest"
imagelinks[103]="http://en.wikipedia.org/wiki/Kepler_Track"
imagelinks[104]="http://en.wikipedia.org/wiki/Porto"
imagelinks[105]="http://en.wikipedia.org/wiki/Sedona,_Arizona"
imagelinks[106]="http://en.wikipedia.org/wiki/Mammoth_Mountain"
imagelinks[107]="http://en.wikipedia.org/wiki/Mammoth_Mountain"
imagelinks[108]="http://en.wikipedia.org/wiki/Mammoth_Mountain"
imagelinks[109]="http://en.wikipedia.org/wiki/Truckee_River"

imagelinks[110]="http://en.wikipedia.org/wiki/Hong_Kong"
imagelinks[111]="http://en.wikipedia.org/wiki/Central_Park"
imagelinks[112]="http://en.wikipedia.org/wiki/Swifts_Creek,_Victoria"

imagelinks[113]="http://en.wikipedia.org/wiki/Huntsville,_Alabama"
imagelinks[114]="http://en.wikipedia.org/wiki/Eden_Project"
imagelinks[115]="http://en.wikipedia.org/wiki/Fraser_River"
imagelinks[116]="http://en.wikipedia.org/wiki/Lanzarote"
imagelinks[117]="http://en.wikipedia.org/wiki/High-speed_rail"
imagelinks[118]="http://en.wikipedia.org/wiki/International_Space_Station"

imagelinks[119]="http://en.wikipedia.org/wiki/The_Nubble_(New_Hampshire)"
imagelinks[120]="http://en.wikipedia.org/wiki/Royal_Gorge_Bridge"
imagelinks[121]="http://en.wikipedia.org/wiki/South_Pole"
imagelinks[122]="http://en.wikipedia.org/wiki/Dallas-Fort_Worth_Metroplex"
imagelinks[123]="http://en.wikipedia.org/wiki/Turks_and_Caicos_Islands"
imagelinks[124]="http://en.wikipedia.org/wiki/Turks_and_Caicos_Islands"

imagelinks[125]="http://en.wikipedia.org/wiki/Adirondack_Park"
imagelinks[126]="http://en.wikipedia.org/wiki/Emerald_Lake_(Yukon)"
imagelinks[127]="http://en.wikipedia.org/wiki/Harrison_Lake"
imagelinks[128]="http://en.wikipedia.org/wiki/Sprague_Lake_(Colorado)"
imagelinks[129]="http://en.wikipedia.org/wiki/Strusta_Lake"
imagelinks[130]="http://en.wikipedia.org/wiki/French_Lake,_California"
imagelinks[131]="http://en.wikipedia.org/wiki/Rhode_Island"
imagelinks[132]="http://en.wikipedia.org/wiki/Phuket_Province"
imagelinks[133]="http://floriansphotographs.blogspot.com/"
imagelinks[134]="http://en.wikipedia.org/wiki/Xinjiang"
imagelinks[135]="http://en.wikipedia.org/wiki/Amboseli"

imagelinks[136]="http://en.wikipedia.org/wiki/Wyoming"
imagelinks[137]="http://en.wikipedia.org/wiki/Western_australia"
imagelinks[138]="http://en.wikipedia.org/wiki/New_hampshire"
imagelinks[139]="http://en.wikipedia.org/wiki/Wisconsin"
imagelinks[140]="http://en.wikipedia.org/wiki/Western_Cape"
imagelinks[141]="http://en.wikipedia.org/wiki/Chandler,_Arizona"
imagelinks[142]="http://en.wikipedia.org/wiki/Moraine_Lake"
imagelinks[143]="http://en.wikipedia.org/wiki/Scotland"
imagelinks[144]="http://en.wikipedia.org/wiki/Scotland"
imagelinks[145]="http://en.wikipedia.org/wiki/Grand_canyon"




var ry=Math.floor(Math.random()*myimages.length)
if (ry==0)
ry=1
document.write('<a href='+'"'+imagelinks[ry]+'"'+'><img src="'+myimages[ry]+'" border=0></a>')
}
random_imglink()
//-->

    <!-- End Random Image Coding -->